In [1]:
import numpy as np
import pandas as pd

In [2]:
pd.set_option("display.max_rows",None)

In [3]:
df = pd.read_csv("job_dataset.csv")
df

,job_id,job_title,company,location,skills_required,experience_years,salary
0,1,Data Analyst,TCS,Hyderabad,Python SQL Excel,1,400000
1,2,Data Scientist,Infosys,Bangalore,Python Machine Learning SQL,3,900000
2,3,Software Engineer,Wipro,Chennai,Java C++ SQL,2,600000
3,4,Machine Learning Engineer,Amazon,Hyderabad,Python Deep Learning ML,4,1200000
4,5,Backend Developer,Google,Bangalore,Python Java SQL,3,1100000
5,6,Frontend Developer,Microsoft,Pune,JavaScript HTML CSS,2,700000
6,7,AI Engineer,Accenture,Hyderabad,Python NLP Deep Learning,5,1500000
7,8,Business Analyst,Capgemini,Mumbai,Excel SQL Power BI,2,650000
8,9,Python Developer,TCS,Chennai,Python Django SQL,1,500000
9,10,SQL Developer,Infosys,Pune,SQL Database ETL,2,550000


In [4]:
df.shape  

(200, 7)

In [5]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
30     False
31     False
32     False
33     False
34     False
35     False
36     False
37     False
38     False
39     False
40     False
41     False
42     False
43     False
44     False
45     False
46     False
47     False
48     False
49     False
50     False
51     False
52     False
53     False
54     False
55     False
56     False
57     False
58     False
59     False
60     False
61     False
62     False
63     False
64     False
65     False
66     False
67     False
68     False
69     False
70     False
71     False
72     False
73     False
74     False
75     False
76     False

In [6]:
df.isnull().sum()

job_id              0
job_title           0
company             0
location            0
skills_required     0
experience_years    0
salary              0
dtype: int64

In [7]:
df = df.drop(['company','location','experience_years','salary'],axis=1)
df

,job_id,job_title,skills_required
0,1,Data Analyst,Python SQL Excel
1,2,Data Scientist,Python Machine Learning SQL
2,3,Software Engineer,Java C++ SQL
3,4,Machine Learning Engineer,Python Deep Learning ML
4,5,Backend Developer,Python Java SQL
5,6,Frontend Developer,JavaScript HTML CSS
6,7,AI Engineer,Python NLP Deep Learning
7,8,Business Analyst,Excel SQL Power BI
8,9,Python Developer,Python Django SQL
9,10,SQL Developer,SQL Database ETL


In [8]:
df["skills_required"].value_counts()

skills_required
Python Django SQL              12
Excel SQL Python               12
Python ML AI                   11
Java OOP SQL                   10
Excel BI SQL                   10
SQL ETL Power BI                7
Python Django API               7
Excel SQL BI                    7
Python Flask API                7
React JS CSS HTML               6
SQL ETL DW                      6
Python ML NLP DL                6
Python ML DL                    6
Python ML NLP                   6
Python AI NLP DL                6
HTML CSS JS React               5
Python API SQL                  5
Python ML DL AI                 5
Java Spring Boot                5
Excel SQL Tableau               5
Java Python API                 5
HTML CSS JS                     5
Python DL NLP                   5
SQL ETL BI                      5
Python DL NLP AI                5
Excel Tableau SQL               2
Python SQL Excel                2
Python ML AI SQL                2
Python Flask SQL                

In [10]:
# converting the text data to feature vectors
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
feature_vectors = vectorizer.fit_transform(df["skills_required"])

In [11]:
vectorizer.get_feature_names_out()

array(['ai', 'api', 'bi', 'boot', 'css', 'data', 'database', 'deep',
       'django', 'dl', 'dw', 'etl', 'excel', 'flask', 'html', 'java',
       'javascript', 'js', 'learning', 'machine', 'ml', 'nlp', 'oop',
       'power', 'python', 'react', 'spring', 'sql', 'tableau',
       'warehousing'], dtype=object)

In [12]:
pd.DataFrame(vectorizer.fit_transform(df["skills_required"]).toarray(),columns=vectorizer.get_feature_names_out())

,ai,api,bi,boot,css,data,database,deep,django,dl,...,ml,nlp,oop,power,python,react,spring,sql,tableau,warehousing
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.449510,0.000000,0.000000,0.489824,0.000000,0.000000
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.206158,0.000000,0.000000,0.224648,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.496219,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.653123,0.000000,0.000000,...,0.363781,0.000000,0.000000,0.000000,0.216838,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.414431,0.000000,0.000000,0.451599,0.000000,0.000000
5,0.000000,0.000000,0.000000,0.000000,0.480071,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.646627,0.000000,0.000000,...,0.000000,0.386665,0.000000,0.000000,0.214681,0.000000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.000000,0.489178,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.689698,0.000000,0.000000,0.000000,0.292747,0.000000,0.000000
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.820452,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.386558,0.000000,0.000000,0.421227,0.000000,0.000000
9,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.836525,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.253207,0.000000,0.000000


In [13]:
# getting the similarity scores using cosine similarity
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.2027078  0.24305974 ... 0.65860833 0.13250584 0.13572004]
 [0.2027078  1.         0.11147435 ... 0.09082339 0.06077108 0.0622452 ]
 [0.24305974 0.11147435 1.         ... 0.20061776 0.         0.13749204]
 ...
 [0.65860833 0.09082339 0.20061776 ... 1.         0.         0.42480838]
 [0.13250584 0.06077108 0.         ... 0.         1.         0.        ]
 [0.13572004 0.0622452  0.13749204 ... 0.42480838 0.         1.        ]]


In [14]:
print(similarity.shape)

(200, 200)


In [15]:
df["job_title"].tolist()

['Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Analyst',
 'Python Developer',
 'SQL Developer',
 'Data Analyst',
 'Data Scientist',
 'Software Engineer',
 'Machine Learning Engineer',
 'Backend Developer',
 'Frontend Developer',
 'AI Engineer',
 'Business Anal

In [18]:
skills = input("Enter your skills: ").split(",")
skills = [skill.strip() for skill in skills]

user_input = " ".join(skills)

user_vector = vectorizer.transform([user_input])

similarity_scores = cosine_similarity(user_vector, feature_vectors)

# flatten the array (2D → 1D)
similarity_scores = similarity_scores.flatten()

# get top 5 indices (highest similarity)
top_5_indices = similarity_scores.argsort()[-10:][::-1]

print("\nTop 5 Job Recommendations:\n")

for i in top_5_indices:
    print(f"Job: {df['job_title'].iloc[i]} |  Match Score: {(similarity_scores[i])}")

Enter your skills:  Python, SQL, HTML, CSS, ML, AI, Power BI



Top 5 Job Recommendations:

Job: Business Analyst |  Match Score: 0.5710123625133774
Job: Business Analyst |  Match Score: 0.5710123625133774
Job: Data Scientist |  Match Score: 0.5525538739873715
Job: Data Scientist |  Match Score: 0.5525538739873715
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
Job: SQL Developer |  Match Score: 0.5404516262003618
